"""Render a ValidationReport as a self-contained static HTML page.

No template engine, no assets: one escaped HTML string with inline CSS, in the
spirit of the guidebook's static output. :func:`write_validation_report`
persists the machine-readable JSON (``report.as_dict()``) and the HTML side by
side so a run always leaves both a viewable and a parseable artifact.
"""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from tablespec.validation.report import ValidationReport

_CSS = """
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica,
       Arial, sans-serif; margin: 2rem auto; max-width: 72rem; color: #1f2328; }
h1 { font-size: 1.4rem; }
.banner { padding: .75rem 1rem; border-radius: 8px; font-weight: 600;
          margin: 1rem 0; }
.banner.pass { background: #dafbe1; color: #116329; }
.banner.fail { background: #ffebe9; color: #a40e26; }
.counts { color: #57606a; margin-bottom: 1rem; }
table { border-collapse: collapse; width: 100%; font-size: .9rem; }
th, td { border-bottom: 1px solid #d0d7de; padding: .4rem .6rem;
         text-align: left; vertical-align: top; }
th { background: #f6f8fa; }
tr.fail td { background: #fff5f5; }
.status { font-weight: 600; }
.status.pass { color: #116329; }
.status.fail { color: #a40e26; }
.severity { text-transform: uppercase; font-size: .75rem; color: #57606a; }
.mono { font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
        font-size: .85rem; }
footer { margin-top: 1.5rem; color: #8b949e; font-size: .8rem; }
"""


def _esc(value: object) -> str:
    return html.escape("" if value is None else str(value))


def render_validation_report_html(
    report: ValidationReport, *, title: str | None = None
) -> str:
    """Render *report* as a single self-contained HTML document."""
    run = report.quality_run
    title = title or f"Validation report: {run.table_name}"
    ok = report.success
    banner_cls = "pass" if ok else "fail"
    banner_text = report.summary()

    rows: list[str] = []
    for r in report.results:
        cls = "pass" if r.success else "fail"
        unexpected = (
            str(r.unexpected_count) if not r.success and r.unexpected_count else ""
        )
        rows.append(
            "<tr class='{cls}'>"
            "<td class='status {cls}'>{status}</td>"
            "<td class='severity'>{severity}</td>"
            "<td class='mono'>{etype}</td>"
            "<td class='mono'>{column}</td>"
            "<td>{description}</td>"
            "<td>{unexpected}</td>"
            "</tr>".format(
                cls=cls,
                status="PASS" if r.success else "FAIL",
                severity=_esc(r.severity),
                etype=_esc(r.expectation_type),
                column=_esc(r.column_name or "-"),
                description=_esc(r.description or ""),
                unexpected=_esc(unexpected),
            )
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{_esc(title)}</title>
<style>{_CSS}</style>
</head>
<body>
<h1>{_esc(title)}</h1>
<div class="banner {banner_cls}">{_esc(banner_text)}</div>
<div class="counts">pipeline {_esc(run.pipeline_name)} &middot; run {_esc(run.run_id)}
 &middot; {_esc(run.run_timestamp)} &middot; {report.passed} passed /
 {report.failed} failed of {report.total}</div>
<table>
<thead><tr><th>Status</th><th>Severity</th><th>Check</th><th>Column</th>
<th>Details</th><th>Unexpected</th></tr></thead>
<tbody>
{"".join(rows)}
</tbody>
</table>
<footer>Generated by tablespec.</footer>
</body>
</html>
"""


def write_validation_report(
    report: ValidationReport,
    out_dir: str | Path,
    *,
    basename: str = "validation-report",
    title: str | None = None,
) -> tuple[Path, Path]:
    """Write *report* as ``<basename>.json`` + ``<basename>.html`` under *out_dir*.

    Returns:
        ``(json_path, html_path)``.
    """
    base = Path(out_dir)
    base.mkdir(parents=True, exist_ok=True)
    json_path = base / f"{basename}.json"
    html_path = base / f"{basename}.html"
    json_path.write_text(
        json.dumps(report.as_dict(), indent=2, default=str), encoding="utf-8"
    )
    html_path.write_text(
        render_validation_report_html(report, title=title), encoding="utf-8"
    )
    return json_path, html_path


__all__ = ["render_validation_report_html", "write_validation_report"]
